// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8XuJZfnuNd7UvNkkshapC6
// Component: MD4kMKQvpO
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import HeaderLogged from "../../HeaderLogged"; // plasmic-import: gLO3qE5tA7/component
import BotoesMenuPrincipal from "../../BotoesMenuPrincipal"; // plasmic-import: 8PboOpLyrBm/component
import Button from "../../Button"; // plasmic-import: CJ-3PKujtR-/component
import Medalha from "../../Medalha"; // plasmic-import: OOiN6jLpGW/component

import { useScreenVariants as useScreenVariantswwY5HaVRu8X4 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: WwY5HA-vRU8x4/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_protect_2_self.module.css"; // plasmic-import: 8XuJZfnuNd7UvNkkshapC6/projectcss
import sty from "./PlasmicTelaMeta.module.css"; // plasmic-import: MD4kMKQvpO/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: H1GZJxswewQ/icon
import LeftArrowSvgrepoComsvgIcon from "./icons/PlasmicIcon__LeftArrowSvgrepoComsvg"; // plasmic-import: fmFspLMBVy/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: hCPX34t0fK3/icon

export type PlasmicTelaMeta__VariantMembers = {};
export type PlasmicTelaMeta__VariantsArgs = {};
type VariantPropType = keyof PlasmicTelaMeta__VariantsArgs;
export const PlasmicTelaMeta__VariantProps = new Array<VariantPropType>();

export type PlasmicTelaMeta__ArgsType = {};
type ArgPropType = keyof PlasmicTelaMeta__ArgsType;
export const PlasmicTelaMeta__ArgProps = new Array<ArgPropType>();

export type PlasmicTelaMeta__OverridesType = {
  root?: p.Flex<"div">;
  headerLogged?: p.Flex<typeof HeaderLogged>;
  columns?: p.Flex<"div">;
  botoesMenuPrincipal?: p.Flex<typeof BotoesMenuPrincipal>;
  button?: p.Flex<typeof Button>;
  svg?: p.Flex<"svg">;
  container?: p.Flex<"div">;
  descricaoMeta?: p.Flex<"div">;
  h5?: p.Flex<"h5">;
  nomeMeta?: p.Flex<"h2">;
  medalha?: p.Flex<typeof Medalha>;
};

export interface DefaultTelaMetaProps {}

function PlasmicTelaMeta__RenderFunc(props: {
  variants: PlasmicTelaMeta__VariantsArgs;
  args: PlasmicTelaMeta__ArgsType;
  overrides: PlasmicTelaMeta__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantswwY5HaVRu8X4()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicTelaMeta.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicTelaMeta.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicTelaMeta.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        {true ? (
          <div
            data-plasmic-name={"root"}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              projectcss.plasmic_tokens,
              sty.root
            )}
          >
            {true ? (
              <HeaderLogged
                data-plasmic-name={"headerLogged"}
                data-plasmic-override={overrides.headerLogged}
                className={classNames("__wab_instance", sty.headerLogged)}
              />
            ) : null}
            {(
              hasVariant(globalVariants, "screen", "mobileOnly") ? true : true
            ) ? (
              <div
                data-plasmic-name={"columns"}
                data-plasmic-override={overrides.columns}
                className={classNames(projectcss.all, sty.columns)}
              >
                <div className={classNames(projectcss.all, sty.column__gIzMf)}>
                  <BotoesMenuPrincipal
                    data-plasmic-name={"botoesMenuPrincipal"}
                    data-plasmic-override={overrides.botoesMenuPrincipal}
                    className={classNames(
                      "__wab_instance",
                      sty.botoesMenuPrincipal
                    )}
                  />
                </div>

                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : true
                ) ? (
                  <div
                    className={classNames(projectcss.all, sty.column__vJhV4)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__hz0Fe)}
                    >
                      <Button
                        data-plasmic-name={"button"}
                        data-plasmic-override={overrides.button}
                        className={classNames("__wab_instance", sty.button)}
                        color={"clear" as const}
                      >
                        <LeftArrowSvgrepoComsvgIcon
                          data-plasmic-name={"svg"}
                          data-plasmic-override={overrides.svg}
                          className={classNames(projectcss.all, sty.svg)}
                          role={"img"}
                        />
                      </Button>
                    </div>

                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <div
                        data-plasmic-name={"container"}
                        data-plasmic-override={overrides.container}
                        className={classNames(projectcss.all, sty.container)}
                      >
                        {true ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__usfcQ
                            )}
                          >
                            <div
                              data-plasmic-name={"descricaoMeta"}
                              data-plasmic-override={overrides.descricaoMeta}
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.descricaoMeta
                              )}
                            >
                              {"texto"}
                            </div>
                          </div>
                        ) : null}

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tEkqh
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            {
                              <h5
                                data-plasmic-name={"h5"}
                                data-plasmic-override={overrides.h5}
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h5,
                                  projectcss.__wab_text,
                                  sty.h5
                                )}
                              >
                                <React.Fragment>
                                  <span
                                    className={
                                      "plasmic_default__all plasmic_default__span"
                                    }
                                    style={{ color: "#757575" }}
                                  >
                                    {"Descrição:"}
                                  </span>
                                </React.Fragment>
                              </h5>
                            }
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </div>

                        {true ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___2VQma
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__gAc0O
                              )}
                            >
                              <React.Fragment>
                                <React.Fragment>{""}</React.Fragment>
                                {
                                  <h2
                                    data-plasmic-name={"nomeMeta"}
                                    data-plasmic-override={overrides.nomeMeta}
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h2,
                                      projectcss.__wab_text,
                                      sty.nomeMeta
                                    )}
                                  >
                                    <React.Fragment>
                                      <span
                                        className={
                                          "plasmic_default__all plasmic_default__span"
                                        }
                                        style={{ color: "#FFFFFF" }}
                                      >
                                        {"Nome Meta"}
                                      </span>
                                    </React.Fragment>
                                  </h2>
                                }
                                <React.Fragment>{""}</React.Fragment>
                              </React.Fragment>
                            </div>

                            <Medalha
                              data-plasmic-name={"medalha"}
                              data-plasmic-override={overrides.medalha}
                              className={classNames(
                                "__wab_instance",
                                sty.medalha
                              )}
                            />
                          </div>
                        ) : null}
                      </div>
                    ) : null}
                  </div>
                ) : null}
              </div>
            ) : null}
          </div>
        ) : null}
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerLogged",
    "columns",
    "botoesMenuPrincipal",
    "button",
    "svg",
    "container",
    "descricaoMeta",
    "h5",
    "nomeMeta",
    "medalha"
  ],
  headerLogged: ["headerLogged"],
  columns: [
    "columns",
    "botoesMenuPrincipal",
    "button",
    "svg",
    "container",
    "descricaoMeta",
    "h5",
    "nomeMeta",
    "medalha"
  ],
  botoesMenuPrincipal: ["botoesMenuPrincipal"],
  button: ["button", "svg"],
  svg: ["svg"],
  container: ["container", "descricaoMeta", "h5", "nomeMeta", "medalha"],
  descricaoMeta: ["descricaoMeta"],
  h5: ["h5"],
  nomeMeta: ["nomeMeta"],
  medalha: ["medalha"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerLogged: typeof HeaderLogged;
  columns: "div";
  botoesMenuPrincipal: typeof BotoesMenuPrincipal;
  button: typeof Button;
  svg: "svg";
  container: "div";
  descricaoMeta: "div";
  h5: "h5";
  nomeMeta: "h2";
  medalha: typeof Medalha;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTelaMeta__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTelaMeta__VariantsArgs;
    args?: PlasmicTelaMeta__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTelaMeta__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicTelaMeta__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTelaMeta__ArgProps,
          internalVariantPropNames: PlasmicTelaMeta__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicTelaMeta__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTelaMeta";
  } else {
    func.displayName = `PlasmicTelaMeta.${nodeName}`;
  }
  return func;
}

export const PlasmicTelaMeta = Object.assign(
  // Top-level PlasmicTelaMeta renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerLogged: makeNodeComponent("headerLogged"),
    columns: makeNodeComponent("columns"),
    botoesMenuPrincipal: makeNodeComponent("botoesMenuPrincipal"),
    button: makeNodeComponent("button"),
    svg: makeNodeComponent("svg"),
    container: makeNodeComponent("container"),
    descricaoMeta: makeNodeComponent("descricaoMeta"),
    h5: makeNodeComponent("h5"),
    nomeMeta: makeNodeComponent("nomeMeta"),
    medalha: makeNodeComponent("medalha"),

    // Metadata about props expected for PlasmicTelaMeta
    internalVariantProps: PlasmicTelaMeta__VariantProps,
    internalArgProps: PlasmicTelaMeta__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Enviar",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicTelaMeta;
/* prettier-ignore-end */
