// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8XuJZfnuNd7UvNkkshapC6
// Component: LQeW26Vvq3
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Medalha from "../../Medalha"; // plasmic-import: OOiN6jLpGW/component
import Button from "../../Button"; // plasmic-import: CJ-3PKujtR-/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_protect_2_self.module.css"; // plasmic-import: 8XuJZfnuNd7UvNkkshapC6/projectcss
import sty from "./PlasmicMiniaturaMeta.module.css"; // plasmic-import: LQeW26Vvq3/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: H1GZJxswewQ/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: hCPX34t0fK3/icon

export type PlasmicMiniaturaMeta__VariantMembers = {
  comMedalha: "comMedalha";
};
export type PlasmicMiniaturaMeta__VariantsArgs = {
  comMedalha?: SingleBooleanChoiceArg<"comMedalha">;
};
type VariantPropType = keyof PlasmicMiniaturaMeta__VariantsArgs;
export const PlasmicMiniaturaMeta__VariantProps = new Array<VariantPropType>(
  "comMedalha"
);

export type PlasmicMiniaturaMeta__ArgsType = {
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
};
type ArgPropType = keyof PlasmicMiniaturaMeta__ArgsType;
export const PlasmicMiniaturaMeta__ArgProps = new Array<ArgPropType>(
  "slot",
  "slot2"
);

export type PlasmicMiniaturaMeta__OverridesType = {
  root?: p.Flex<"div">;
  medalha?: p.Flex<typeof Medalha>;
  registra?: p.Flex<typeof Button>;
};

export interface DefaultMiniaturaMetaProps {
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  comMedalha?: SingleBooleanChoiceArg<"comMedalha">;
  className?: string;
}

function PlasmicMiniaturaMeta__RenderFunc(props: {
  variants: PlasmicMiniaturaMeta__VariantsArgs;
  args: PlasmicMiniaturaMeta__ArgsType;
  overrides: PlasmicMiniaturaMeta__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const stateSpecs = React.useMemo(
    () => [
      {
        path: "comMedalha",
        type: "private",
        initFunc: ($props, $state, $ctx) => $props.comMedalha
      }
    ],
    [$props, $ctx]
  );
  const $state = p.useDollarState(stateSpecs, $props, $ctx);

  const [$queries, setDollarQueries] = React.useState({});

  return (
    true ? (
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          sty.root
        )}
      >
        <div className={classNames(projectcss.all, sty.freeBox__cowRf)}>
          {true ? (
            <div className={classNames(projectcss.all, sty.freeBox__noCej)}>
              <div className={classNames(projectcss.all, sty.freeBox__mfpq)}>
                {p.renderPlasmicSlot({
                  defaultContents: (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2QyHl
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__cOk5
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#FFFFFF" }}
                              >
                                {"Meta"}
                              </span>
                            </React.Fragment>
                          </h4>
                        }
                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    </div>
                  ),

                  value: args.slot
                })}
              </div>

              {(
                hasVariant($state, "comMedalha", "comMedalha") ? true : true
              ) ? (
                <Medalha
                  data-plasmic-name={"medalha"}
                  data-plasmic-override={overrides.medalha}
                  className={classNames("__wab_instance", sty.medalha, {
                    [sty.medalhacomMedalha]: hasVariant(
                      $state,
                      "comMedalha",
                      "comMedalha"
                    )
                  })}
                  miniatura={true}
                />
              ) : null}
            </div>
          ) : null}

          <div className={classNames(projectcss.all, sty.freeBox___6ExQ)}>
            {p.renderPlasmicSlot({
              defaultContents: (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fMtNj
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#D3D3D3" }}
                    >
                      {"Sequencia"}
                    </span>
                  </React.Fragment>
                </div>
              ),

              value: args.slot2
            })}
          </div>
        </div>

        <Button
          data-plasmic-name={"registra"}
          data-plasmic-override={overrides.registra}
          className={classNames("__wab_instance", sty.registra, {
            [sty.registracomMedalha]: hasVariant(
              $state,
              "comMedalha",
              "comMedalha"
            )
          })}
          color={"yellow" as const}
        >
          {"Registrar"}
        </Button>
      </div>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "medalha", "registra"],
  medalha: ["medalha"],
  registra: ["registra"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  medalha: typeof Medalha;
  registra: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMiniaturaMeta__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMiniaturaMeta__VariantsArgs;
    args?: PlasmicMiniaturaMeta__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMiniaturaMeta__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicMiniaturaMeta__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicMiniaturaMeta__ArgProps,
          internalVariantPropNames: PlasmicMiniaturaMeta__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicMiniaturaMeta__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMiniaturaMeta";
  } else {
    func.displayName = `PlasmicMiniaturaMeta.${nodeName}`;
  }
  return func;
}

export const PlasmicMiniaturaMeta = Object.assign(
  // Top-level PlasmicMiniaturaMeta renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    medalha: makeNodeComponent("medalha"),
    registra: makeNodeComponent("registra"),

    // Metadata about props expected for PlasmicMiniaturaMeta
    internalVariantProps: PlasmicMiniaturaMeta__VariantProps,
    internalArgProps: PlasmicMiniaturaMeta__ArgProps
  }
);

export default PlasmicMiniaturaMeta;
/* prettier-ignore-end */
