// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8XuJZfnuNd7UvNkkshapC6
// Component: cHNTWN6IIi
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: Cew9iEQBJMu/component
import HelpingHand from "../../HelpingHand"; // plasmic-import: 0GtKHl4SJA/component
import Button from "../../Button"; // plasmic-import: CJ-3PKujtR-/component
import TextInput from "../../TextInput"; // plasmic-import: 7q4dYfz6E__/component
import PasswordInput from "../../PasswordInput"; // plasmic-import: s963UX2uFqp/component

import { useScreenVariants as useScreenVariantswwY5HaVRu8X4 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: WwY5HA-vRU8x4/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_protect_2_self.module.css"; // plasmic-import: 8XuJZfnuNd7UvNkkshapC6/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: cHNTWN6IIi/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: H1GZJxswewQ/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: hCPX34t0fK3/icon
import SearchsvgIcon from "./icons/PlasmicIcon__Searchsvg"; // plasmic-import: WK-uNEKVCw3/icon

export type PlasmicHomepage__VariantMembers = {
  loginScreen: "loginScreen";
};

export type PlasmicHomepage__VariantsArgs = {
  loginScreen?: SingleBooleanChoiceArg<"loginScreen">;
};

type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>(
  "loginScreen"
);

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  columns?: p.Flex<"div">;
  helpingHand?: p.Flex<typeof HelpingHand>;
  fraseMj?: p.Flex<"div">;
  entrar?: p.Flex<typeof Button>;
  button?: p.Flex<typeof Button>;
  textInput?: p.Flex<typeof TextInput>;
  passwordInput?: p.Flex<typeof PasswordInput>;
  logar?: p.Flex<typeof Button>;
  logarComGoogle?: p.Flex<typeof Button>;
  img?: p.Flex<typeof p.PlasmicImg>;
  link?: p.Flex<"a"> & Partial<LinkProps>;
  textbox?: p.Flex<typeof TextInput>;
};

export interface DefaultHomepageProps {}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantswwY5HaVRu8X4()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root,
            {
              [sty.rootloginScreen]: hasVariant(
                variants,
                "loginScreen",
                "loginScreen"
              )
            }
          )}
        >
          <div
            className={classNames(projectcss.all, sty.freeBox__pjoUe, {
              [sty.freeBoxloginScreen__pjoUe7UOhc]: hasVariant(
                variants,
                "loginScreen",
                "loginScreen"
              )
            })}
          >
            {true ? (
              <Header
                data-plasmic-name={"header"}
                data-plasmic-override={overrides.header}
                className={classNames("__wab_instance", sty.header)}
                line={"on" as const}
              />
            ) : null}
            {true ? (
              <div
                data-plasmic-name={"columns"}
                data-plasmic-override={overrides.columns}
                className={classNames(projectcss.all, sty.columns, {
                  [sty.columnsloginScreen]: hasVariant(
                    variants,
                    "loginScreen",
                    "loginScreen"
                  )
                })}
              >
                <div
                  className={classNames(projectcss.all, sty.column__pFFvJ, {
                    [sty.columnloginScreen__pFFvJ7UOhc]: hasVariant(
                      variants,
                      "loginScreen",
                      "loginScreen"
                    )
                  })}
                >
                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__vX7VN)}
                    >
                      <HelpingHand
                        data-plasmic-name={"helpingHand"}
                        data-plasmic-override={overrides.helpingHand}
                        className={classNames(
                          "__wab_instance",
                          sty.helpingHand
                        )}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ksUMr,
                            {
                              [sty.freeBoxloginScreen__ksUMr7UOhc]: hasVariant(
                                variants,
                                "loginScreen",
                                "loginScreen"
                              )
                            }
                          )}
                        >
                          <div
                            data-plasmic-name={"fraseMj"}
                            data-plasmic-override={overrides.fraseMj}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.fraseMj,
                              {
                                [sty.fraseMjloginScreen]: hasVariant(
                                  variants,
                                  "loginScreen",
                                  "loginScreen"
                                )
                              }
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <h1
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.h1,
                                    projectcss.__wab_text,
                                    sty.h1__jVhzB
                                  )}
                                >
                                  <React.Fragment>
                                    <React.Fragment>{""}</React.Fragment>
                                    {
                                      <h2
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h2,
                                          projectcss.__wab_text,
                                          sty.h2__unPmu,
                                          {
                                            [sty.h2loginScreen__unPmu7UOhc]:
                                              hasVariant(
                                                variants,
                                                "loginScreen",
                                                "loginScreen"
                                              )
                                          }
                                        )}
                                      >
                                        <React.Fragment>
                                          <span
                                            className={
                                              "plasmic_default__all plasmic_default__span"
                                            }
                                            style={{ color: "#FFFCFC" }}
                                          >
                                            {"O talento vence jogos, mas só o"}
                                          </span>
                                          <React.Fragment>
                                            {"\n"}
                                          </React.Fragment>
                                          {
                                            <h1
                                              className={classNames(
                                                projectcss.all,
                                                projectcss.h1,
                                                projectcss.__wab_text,
                                                sty.h1__sIcty,
                                                {
                                                  [sty.h1loginScreen__sIcty7UOhc]:
                                                    hasVariant(
                                                      variants,
                                                      "loginScreen",
                                                      "loginScreen"
                                                    )
                                                }
                                              )}
                                            >
                                              {hasVariant(
                                                variants,
                                                "loginScreen",
                                                "loginScreen"
                                              ) ? (
                                                <React.Fragment>
                                                  <React.Fragment>
                                                    {""}
                                                  </React.Fragment>
                                                  {
                                                    <h1
                                                      className={classNames(
                                                        projectcss.all,
                                                        projectcss.h1,
                                                        projectcss.__wab_text,
                                                        sty.h1___2GWsC,
                                                        {
                                                          [sty.h1loginScreen___2GWsC7UOhc]:
                                                            hasVariant(
                                                              variants,
                                                              "loginScreen",
                                                              "loginScreen"
                                                            )
                                                        }
                                                      )}
                                                    >
                                                      {hasVariant(
                                                        variants,
                                                        "loginScreen",
                                                        "loginScreen"
                                                      ) ? (
                                                        <React.Fragment>
                                                          <React.Fragment>
                                                            {""}
                                                          </React.Fragment>
                                                          {
                                                            <h2
                                                              className={classNames(
                                                                projectcss.all,
                                                                projectcss.h2,
                                                                projectcss.__wab_text,
                                                                sty.h2___9GsgP,
                                                                {
                                                                  [sty.h2loginScreen___9GsgP7UOhc]:
                                                                    hasVariant(
                                                                      variants,
                                                                      "loginScreen",
                                                                      "loginScreen"
                                                                    )
                                                                }
                                                              )}
                                                            >
                                                              {hasVariant(
                                                                variants,
                                                                "loginScreen",
                                                                "loginScreen"
                                                              ) ? (
                                                                <React.Fragment>
                                                                  <React.Fragment>
                                                                    {""}
                                                                  </React.Fragment>
                                                                  {
                                                                    <h1
                                                                      className={classNames(
                                                                        projectcss.all,
                                                                        projectcss.h1,
                                                                        projectcss.__wab_text,
                                                                        sty.h1__cbqH,
                                                                        {
                                                                          [sty.h1loginScreen__cbqH7UOhc]:
                                                                            hasVariant(
                                                                              variants,
                                                                              "loginScreen",
                                                                              "loginScreen"
                                                                            )
                                                                        }
                                                                      )}
                                                                    >
                                                                      {hasVariant(
                                                                        variants,
                                                                        "loginScreen",
                                                                        "loginScreen"
                                                                      ) &&
                                                                      hasVariant(
                                                                        globalVariants,
                                                                        "screen",
                                                                        "tablet"
                                                                      ) ? (
                                                                        <React.Fragment>
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                          {
                                                                            <h2
                                                                              className={classNames(
                                                                                projectcss.all,
                                                                                projectcss.h2,
                                                                                projectcss.__wab_text,
                                                                                sty.h2__pNo9E,
                                                                                {
                                                                                  [sty.h2loginScreen__pNo9E7UOhc]:
                                                                                    hasVariant(
                                                                                      variants,
                                                                                      "loginScreen",
                                                                                      "loginScreen"
                                                                                    )
                                                                                }
                                                                              )}
                                                                            >
                                                                              {hasVariant(
                                                                                variants,
                                                                                "loginScreen",
                                                                                "loginScreen"
                                                                              ) &&
                                                                              hasVariant(
                                                                                globalVariants,
                                                                                "screen",
                                                                                "mobileOnly"
                                                                              ) ? (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC",
                                                                                      fontWeight: 900
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "trabalho em equipe ganha campeonatos."
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              ) : hasVariant(
                                                                                  variants,
                                                                                  "loginScreen",
                                                                                  "loginScreen"
                                                                                ) &&
                                                                                hasVariant(
                                                                                  globalVariants,
                                                                                  "screen",
                                                                                  "tablet"
                                                                                ) ? (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC",
                                                                                      fontWeight: 900
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "trabalho em equipe ganha campeonatos."
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              ) : (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "trabalho em equipe ganha campeonatos."
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              )}
                                                                            </h2>
                                                                          }
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                        </React.Fragment>
                                                                      ) : (
                                                                        <React.Fragment>
                                                                          <span
                                                                            className={
                                                                              "plasmic_default__all plasmic_default__span"
                                                                            }
                                                                            style={{
                                                                              color:
                                                                                "#FFFCFC"
                                                                            }}
                                                                          >
                                                                            {
                                                                              "trabalho em equipe ganha campeonatos."
                                                                            }
                                                                          </span>
                                                                        </React.Fragment>
                                                                      )}
                                                                    </h1>
                                                                  }
                                                                  <React.Fragment>
                                                                    {""}
                                                                  </React.Fragment>
                                                                  {
                                                                    <h4
                                                                      className={classNames(
                                                                        projectcss.all,
                                                                        projectcss.h4,
                                                                        projectcss.__wab_text,
                                                                        sty.h4__kQDk1,
                                                                        {
                                                                          [sty.h4loginScreen__kQDk17UOhc]:
                                                                            hasVariant(
                                                                              variants,
                                                                              "loginScreen",
                                                                              "loginScreen"
                                                                            )
                                                                        }
                                                                      )}
                                                                    >
                                                                      {hasVariant(
                                                                        variants,
                                                                        "loginScreen",
                                                                        "loginScreen"
                                                                      ) ? (
                                                                        <React.Fragment>
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                          {
                                                                            <h3
                                                                              className={classNames(
                                                                                projectcss.all,
                                                                                projectcss.h3,
                                                                                projectcss.__wab_text,
                                                                                sty.h3__yjYb8,
                                                                                {
                                                                                  [sty.h3loginScreen__yjYb87UOhc]:
                                                                                    hasVariant(
                                                                                      variants,
                                                                                      "loginScreen",
                                                                                      "loginScreen"
                                                                                    )
                                                                                }
                                                                              )}
                                                                            >
                                                                              {hasVariant(
                                                                                variants,
                                                                                "loginScreen",
                                                                                "loginScreen"
                                                                              ) ? (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "-Michael Jordan"
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              ) : (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "-Michael Jordan"
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              )}
                                                                            </h3>
                                                                          }
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                        </React.Fragment>
                                                                      ) : (
                                                                        <React.Fragment>
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                          {
                                                                            <h3
                                                                              className={classNames(
                                                                                projectcss.all,
                                                                                projectcss.h3,
                                                                                projectcss.__wab_text,
                                                                                sty.h3__yjYb8,
                                                                                {
                                                                                  [sty.h3loginScreen__yjYb87UOhc]:
                                                                                    hasVariant(
                                                                                      variants,
                                                                                      "loginScreen",
                                                                                      "loginScreen"
                                                                                    )
                                                                                }
                                                                              )}
                                                                            >
                                                                              {hasVariant(
                                                                                variants,
                                                                                "loginScreen",
                                                                                "loginScreen"
                                                                              ) ? (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "-Michael Jordan"
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              ) : (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "-Michael Jordan"
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              )}
                                                                            </h3>
                                                                          }
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                        </React.Fragment>
                                                                      )}
                                                                    </h4>
                                                                  }
                                                                  <React.Fragment>
                                                                    {""}
                                                                  </React.Fragment>
                                                                </React.Fragment>
                                                              ) : (
                                                                <React.Fragment>
                                                                  <span
                                                                    className={
                                                                      "plasmic_default__all plasmic_default__span"
                                                                    }
                                                                    style={{
                                                                      color:
                                                                        "#FFFCFC"
                                                                    }}
                                                                  >
                                                                    {
                                                                      "trabalho em equipe ganha campeonatos."
                                                                    }
                                                                  </span>
                                                                  <React.Fragment>
                                                                    {"\n"}
                                                                  </React.Fragment>
                                                                  {
                                                                    <h4
                                                                      className={classNames(
                                                                        projectcss.all,
                                                                        projectcss.h4,
                                                                        projectcss.__wab_text,
                                                                        sty.h4__kQDk1,
                                                                        {
                                                                          [sty.h4loginScreen__kQDk17UOhc]:
                                                                            hasVariant(
                                                                              variants,
                                                                              "loginScreen",
                                                                              "loginScreen"
                                                                            )
                                                                        }
                                                                      )}
                                                                    >
                                                                      {hasVariant(
                                                                        variants,
                                                                        "loginScreen",
                                                                        "loginScreen"
                                                                      ) ? (
                                                                        <React.Fragment>
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                          {
                                                                            <h3
                                                                              className={classNames(
                                                                                projectcss.all,
                                                                                projectcss.h3,
                                                                                projectcss.__wab_text,
                                                                                sty.h3__yjYb8,
                                                                                {
                                                                                  [sty.h3loginScreen__yjYb87UOhc]:
                                                                                    hasVariant(
                                                                                      variants,
                                                                                      "loginScreen",
                                                                                      "loginScreen"
                                                                                    )
                                                                                }
                                                                              )}
                                                                            >
                                                                              {hasVariant(
                                                                                variants,
                                                                                "loginScreen",
                                                                                "loginScreen"
                                                                              ) ? (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "-Michael Jordan"
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              ) : (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "-Michael Jordan"
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              )}
                                                                            </h3>
                                                                          }
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                        </React.Fragment>
                                                                      ) : (
                                                                        <React.Fragment>
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                          {
                                                                            <h3
                                                                              className={classNames(
                                                                                projectcss.all,
                                                                                projectcss.h3,
                                                                                projectcss.__wab_text,
                                                                                sty.h3__yjYb8,
                                                                                {
                                                                                  [sty.h3loginScreen__yjYb87UOhc]:
                                                                                    hasVariant(
                                                                                      variants,
                                                                                      "loginScreen",
                                                                                      "loginScreen"
                                                                                    )
                                                                                }
                                                                              )}
                                                                            >
                                                                              {hasVariant(
                                                                                variants,
                                                                                "loginScreen",
                                                                                "loginScreen"
                                                                              ) ? (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "-Michael Jordan"
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              ) : (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "-Michael Jordan"
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              )}
                                                                            </h3>
                                                                          }
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                        </React.Fragment>
                                                                      )}
                                                                    </h4>
                                                                  }
                                                                  <React.Fragment>
                                                                    {""}
                                                                  </React.Fragment>
                                                                </React.Fragment>
                                                              )}
                                                            </h2>
                                                          }
                                                          <React.Fragment>
                                                            {""}
                                                          </React.Fragment>
                                                        </React.Fragment>
                                                      ) : (
                                                        <React.Fragment>
                                                          <span
                                                            className={
                                                              "plasmic_default__all plasmic_default__span"
                                                            }
                                                            style={{
                                                              color: "#FFFCFC"
                                                            }}
                                                          >
                                                            {
                                                              "trabalho em equipe ganha campeonatos."
                                                            }
                                                          </span>
                                                          <React.Fragment>
                                                            {"\n"}
                                                          </React.Fragment>
                                                          {
                                                            <h4
                                                              className={classNames(
                                                                projectcss.all,
                                                                projectcss.h4,
                                                                projectcss.__wab_text,
                                                                sty.h4__xrgEc
                                                              )}
                                                            >
                                                              <React.Fragment>
                                                                <React.Fragment>
                                                                  {""}
                                                                </React.Fragment>
                                                                {
                                                                  <h3
                                                                    className={classNames(
                                                                      projectcss.all,
                                                                      projectcss.h3,
                                                                      projectcss.__wab_text,
                                                                      sty.h3__a0X8
                                                                    )}
                                                                  >
                                                                    <React.Fragment>
                                                                      <span
                                                                        className={
                                                                          "plasmic_default__all plasmic_default__span"
                                                                        }
                                                                        style={{
                                                                          color:
                                                                            "#FFFCFC"
                                                                        }}
                                                                      >
                                                                        {
                                                                          "-Michael Jordan"
                                                                        }
                                                                      </span>
                                                                    </React.Fragment>
                                                                  </h3>
                                                                }
                                                                <React.Fragment>
                                                                  {""}
                                                                </React.Fragment>
                                                              </React.Fragment>
                                                            </h4>
                                                          }
                                                          <React.Fragment>
                                                            {""}
                                                          </React.Fragment>
                                                        </React.Fragment>
                                                      )}
                                                    </h1>
                                                  }
                                                  <React.Fragment>
                                                    {""}
                                                  </React.Fragment>
                                                </React.Fragment>
                                              ) : (
                                                <React.Fragment>
                                                  <span
                                                    className={
                                                      "plasmic_default__all plasmic_default__span"
                                                    }
                                                    style={{ color: "#FFFCFC" }}
                                                  >
                                                    {
                                                      "trabalho em equipe ganha campeonatos."
                                                    }
                                                  </span>
                                                  <React.Fragment>
                                                    {"\n"}
                                                  </React.Fragment>
                                                  {
                                                    <h4
                                                      className={classNames(
                                                        projectcss.all,
                                                        projectcss.h4,
                                                        projectcss.__wab_text,
                                                        sty.h4__enfjC
                                                      )}
                                                    >
                                                      <React.Fragment>
                                                        <React.Fragment>
                                                          {""}
                                                        </React.Fragment>
                                                        {
                                                          <h3
                                                            className={classNames(
                                                              projectcss.all,
                                                              projectcss.h3,
                                                              projectcss.__wab_text,
                                                              sty.h3__cuPtL
                                                            )}
                                                          >
                                                            <React.Fragment>
                                                              <span
                                                                className={
                                                                  "plasmic_default__all plasmic_default__span"
                                                                }
                                                                style={{
                                                                  color:
                                                                    "#FFFCFC"
                                                                }}
                                                              >
                                                                {
                                                                  "-Michael Jordan"
                                                                }
                                                              </span>
                                                            </React.Fragment>
                                                          </h3>
                                                        }
                                                        <React.Fragment>
                                                          {""}
                                                        </React.Fragment>
                                                      </React.Fragment>
                                                    </h4>
                                                  }
                                                  <React.Fragment>
                                                    {""}
                                                  </React.Fragment>
                                                </React.Fragment>
                                              )}
                                            </h1>
                                          }
                                          <React.Fragment>{""}</React.Fragment>
                                        </React.Fragment>
                                      </h2>
                                    }
                                    <React.Fragment>{""}</React.Fragment>
                                  </React.Fragment>
                                </h1>
                              }
                              <React.Fragment>{""}</React.Fragment>
                            </React.Fragment>
                          </div>
                        </div>
                      ) : null}
                    </div>
                  ) : null}
                </div>

                <div
                  className={classNames(projectcss.all, sty.column__qfE1, {
                    [sty.columnloginScreen__qfE17UOhc]: hasVariant(
                      variants,
                      "loginScreen",
                      "loginScreen"
                    )
                  })}
                >
                  {(
                    hasVariant(variants, "loginScreen", "loginScreen")
                      ? true
                      : true
                  ) ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__vter, {
                        [sty.freeBoxloginScreen__vter7UOhc]: hasVariant(
                          variants,
                          "loginScreen",
                          "loginScreen"
                        )
                      })}
                    >
                      <Button
                        data-plasmic-name={"entrar"}
                        data-plasmic-override={overrides.entrar}
                        className={classNames("__wab_instance", sty.entrar)}
                        color={"white" as const}
                        shape={"rounded" as const}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wnB9I
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            {
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__bQXl
                                )}
                              >
                                {"Entrar"}
                              </h3>
                            }
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </div>
                      </Button>

                      <Button
                        data-plasmic-name={"button"}
                        data-plasmic-override={overrides.button}
                        className={classNames("__wab_instance", sty.button)}
                        color={"yellow" as const}
                        link={`/criar-conta`}
                        shape={"rounded" as const}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zqGRt
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{""}</React.Fragment>
                            {
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3___4Pf5Q
                                )}
                              >
                                {"Registre-se"}
                              </h3>
                            }
                            <React.Fragment>{""}</React.Fragment>
                          </React.Fragment>
                        </div>
                      </Button>
                    </div>
                  ) : null}
                  {(
                    hasVariant(variants, "loginScreen", "loginScreen")
                      ? true
                      : false
                  ) ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox__noxk4,
                        {
                          [sty.freeBoxloginScreen__noxk47UOhc]: hasVariant(
                            variants,
                            "loginScreen",
                            "loginScreen"
                          )
                        }
                      )}
                    >
                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__dsZke,
                            {
                              [sty.freeBoxloginScreen__dsZke7UOhc]: hasVariant(
                                variants,
                                "loginScreen",
                                "loginScreen"
                              )
                            }
                          )}
                        >
                          <TextInput
                            data-plasmic-name={"textInput"}
                            data-plasmic-override={overrides.textInput}
                            className={classNames(
                              "__wab_instance",
                              sty.textInput,
                              {
                                [sty.textInputloginScreen]: hasVariant(
                                  variants,
                                  "loginScreen",
                                  "loginScreen"
                                )
                              }
                            )}
                            id={
                              hasVariant(variants, "loginScreen", "loginScreen")
                                ? ("nome" as const)
                                : undefined
                            }
                          />

                          <PasswordInput
                            data-plasmic-name={"passwordInput"}
                            data-plasmic-override={overrides.passwordInput}
                            className={classNames(
                              "__wab_instance",
                              sty.passwordInput,
                              {
                                [sty.passwordInputloginScreen]: hasVariant(
                                  variants,
                                  "loginScreen",
                                  "loginScreen"
                                )
                              }
                            )}
                            color={
                              hasVariant(variants, "loginScreen", "loginScreen")
                                ? ("dark" as const)
                                : undefined
                            }
                            id={
                              hasVariant(variants, "loginScreen", "loginScreen")
                                ? ("senha" as const)
                                : undefined
                            }
                          />

                          <Button
                            data-plasmic-name={"logar"}
                            data-plasmic-override={overrides.logar}
                            className={classNames("__wab_instance", sty.logar, {
                              [sty.logarloginScreen]: hasVariant(
                                variants,
                                "loginScreen",
                                "loginScreen"
                              )
                            })}
                            color={"yellow" as const}
                          >
                            {"Entrar"}
                          </Button>

                          {true ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__rIql9
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__adYZj
                                )}
                              >
                                <React.Fragment>
                                  <span
                                    className={
                                      "plasmic_default__all plasmic_default__span"
                                    }
                                    style={{ color: "#FFFFFF" }}
                                  >
                                    {"Ou"}
                                  </span>
                                </React.Fragment>
                              </div>
                            </div>
                          ) : null}

                          <Button
                            data-plasmic-name={"logarComGoogle"}
                            data-plasmic-override={overrides.logarComGoogle}
                            className={classNames(
                              "__wab_instance",
                              sty.logarComGoogle,
                              {
                                [sty.logarComGoogleloginScreen]: hasVariant(
                                  variants,
                                  "loginScreen",
                                  "loginScreen"
                                )
                              }
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__hDd67
                              )}
                            >
                              {"Entre com "}
                            </div>

                            <p.PlasmicImg
                              data-plasmic-name={"img"}
                              data-plasmic-override={overrides.img}
                              alt={""}
                              className={classNames(sty.img)}
                              displayHeight={"23px" as const}
                              displayMaxHeight={"none" as const}
                              displayMaxWidth={"100%" as const}
                              displayMinHeight={"0" as const}
                              displayMinWidth={"0" as const}
                              displayWidth={"auto" as const}
                              loading={"lazy" as const}
                              src={{
                                src: "/plasmic/protect_2_self/images/googleGLogosvgpng.png",
                                fullWidth: 768,
                                fullHeight: 768,
                                aspectRatio: undefined
                              }}
                            />
                          </Button>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rzLjS
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#FFFFFF" }}
                              >
                                {"Ainda não tem conta? Registre-se "}
                              </span>
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <p.PlasmicLink
                                  data-plasmic-name={"link"}
                                  data-plasmic-override={overrides.link}
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.a,
                                    projectcss.__wab_text,
                                    projectcss.plasmic_default__inline,
                                    sty.link
                                  )}
                                  component={Link}
                                  href={`/criar-conta`}
                                  platform={"nextjs"}
                                >
                                  <React.Fragment>
                                    <span
                                      className={
                                        "plasmic_default__all plasmic_default__span"
                                      }
                                      style={{ color: "#00B5FF" }}
                                    >
                                      {"aqui"}
                                    </span>
                                  </React.Fragment>
                                </p.PlasmicLink>
                              }
                              <React.Fragment>{""}</React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#FFFFFF" }}
                              >
                                {"!"}
                              </span>
                            </React.Fragment>
                          </div>
                        </div>
                      ) : null}
                    </div>
                  ) : null}
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "columns",
    "helpingHand",
    "fraseMj",
    "entrar",
    "button",
    "textInput",
    "textbox",
    "passwordInput",
    "logar",
    "logarComGoogle",
    "img",
    "link"
  ],
  header: ["header"],
  columns: [
    "columns",
    "helpingHand",
    "fraseMj",
    "entrar",
    "button",
    "textInput",
    "textbox",
    "passwordInput",
    "logar",
    "logarComGoogle",
    "img",
    "link"
  ],
  helpingHand: ["helpingHand"],
  fraseMj: ["fraseMj"],
  entrar: ["entrar"],
  button: ["button"],
  textInput: ["textInput", "textbox"],
  passwordInput: ["passwordInput"],
  logar: ["logar"],
  logarComGoogle: ["logarComGoogle", "img"],
  img: ["img"],
  link: ["link"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  columns: "div";
  helpingHand: typeof HelpingHand;
  fraseMj: "div";
  entrar: typeof Button;
  button: typeof Button;
  textInput: typeof TextInput;
  passwordInput: typeof PasswordInput;
  logar: typeof Button;
  logarComGoogle: typeof Button;
  img: typeof p.PlasmicImg;
  link: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    columns: makeNodeComponent("columns"),
    helpingHand: makeNodeComponent("helpingHand"),
    fraseMj: makeNodeComponent("fraseMj"),
    entrar: makeNodeComponent("entrar"),
    button: makeNodeComponent("button"),
    textInput: makeNodeComponent("textInput"),
    passwordInput: makeNodeComponent("passwordInput"),
    logar: makeNodeComponent("logar"),
    logarComGoogle: makeNodeComponent("logarComGoogle"),
    img: makeNodeComponent("img"),
    link: makeNodeComponent("link"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
