// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8XuJZfnuNd7UvNkkshapC6
// Component: cHNTWN6IIi
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: Cew9iEQBJMu/component
import HelpingHand from "../../HelpingHand"; // plasmic-import: 0GtKHl4SJA/component
import SignInUp from "../../SignInUp"; // plasmic-import: tRAjWGA5Mr/component
import Login from "../../Login"; // plasmic-import: rtdQhdscRZ1/component

import { useScreenVariants as useScreenVariantswwY5HaVRu8X4 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: WwY5HA-vRU8x4/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_protect_2_self.module.css"; // plasmic-import: 8XuJZfnuNd7UvNkkshapC6/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: cHNTWN6IIi/css

export type PlasmicHomepage__VariantMembers = {
  login: "login";
};

export type PlasmicHomepage__VariantsArgs = {
  login?: SingleBooleanChoiceArg<"login">;
};

type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>(
  "login"
);

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  columns?: p.Flex<"div">;
  helpingHand?: p.Flex<typeof HelpingHand>;
  fraseMj?: p.Flex<"div">;
  signInUp?: p.Flex<typeof SignInUp>;
  login?: p.Flex<typeof Login>;
};

export interface DefaultHomepageProps {}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantswwY5HaVRu8X4()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root,
            { [sty.rootlogin]: hasVariant(variants, "login", "login") }
          )}
        >
          <div
            className={classNames(projectcss.all, sty.freeBox__pjoUe, {
              [sty.freeBoxlogin__pjoUe7UOhc]: hasVariant(
                variants,
                "login",
                "login"
              )
            })}
          >
            {true ? (
              <Header
                data-plasmic-name={"header"}
                data-plasmic-override={overrides.header}
                className={classNames("__wab_instance", sty.header)}
                line={"on" as const}
              />
            ) : null}
            {true ? (
              <div
                data-plasmic-name={"columns"}
                data-plasmic-override={overrides.columns}
                className={classNames(projectcss.all, sty.columns, {
                  [sty.columnslogin]: hasVariant(variants, "login", "login")
                })}
              >
                <div
                  className={classNames(projectcss.all, sty.column__pFFvJ, {
                    [sty.columnlogin__pFFvJ7UOhc]: hasVariant(
                      variants,
                      "login",
                      "login"
                    )
                  })}
                >
                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__vX7VN)}
                    >
                      <HelpingHand
                        data-plasmic-name={"helpingHand"}
                        data-plasmic-override={overrides.helpingHand}
                        className={classNames(
                          "__wab_instance",
                          sty.helpingHand
                        )}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ksUMr,
                            {
                              [sty.freeBoxlogin__ksUMr7UOhc]: hasVariant(
                                variants,
                                "login",
                                "login"
                              )
                            }
                          )}
                        >
                          <div
                            data-plasmic-name={"fraseMj"}
                            data-plasmic-override={overrides.fraseMj}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.fraseMj,
                              {
                                [sty.fraseMjlogin]: hasVariant(
                                  variants,
                                  "login",
                                  "login"
                                )
                              }
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <h1
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.h1,
                                    projectcss.__wab_text,
                                    sty.h1__jVhzB
                                  )}
                                >
                                  <React.Fragment>
                                    <React.Fragment>{""}</React.Fragment>
                                    {
                                      <h2
                                        className={classNames(
                                          projectcss.all,
                                          projectcss.h2,
                                          projectcss.__wab_text,
                                          sty.h2__unPmu,
                                          {
                                            [sty.h2login__unPmu7UOhc]:
                                              hasVariant(
                                                variants,
                                                "login",
                                                "login"
                                              )
                                          }
                                        )}
                                      >
                                        <React.Fragment>
                                          <span
                                            className={
                                              "plasmic_default__all plasmic_default__span"
                                            }
                                            style={{ color: "#FFFCFC" }}
                                          >
                                            {"O talento vence jogos, mas só o"}
                                          </span>
                                          <React.Fragment>
                                            {"\n"}
                                          </React.Fragment>
                                          {
                                            <h1
                                              className={classNames(
                                                projectcss.all,
                                                projectcss.h1,
                                                projectcss.__wab_text,
                                                sty.h1__sIcty,
                                                {
                                                  [sty.h1login__sIcty7UOhc]:
                                                    hasVariant(
                                                      variants,
                                                      "login",
                                                      "login"
                                                    )
                                                }
                                              )}
                                            >
                                              {hasVariant(
                                                variants,
                                                "login",
                                                "login"
                                              ) ? (
                                                <React.Fragment>
                                                  <React.Fragment>
                                                    {""}
                                                  </React.Fragment>
                                                  {
                                                    <h1
                                                      className={classNames(
                                                        projectcss.all,
                                                        projectcss.h1,
                                                        projectcss.__wab_text,
                                                        sty.h1___2GWsC,
                                                        {
                                                          [sty.h1login___2GWsC7UOhc]:
                                                            hasVariant(
                                                              variants,
                                                              "login",
                                                              "login"
                                                            )
                                                        }
                                                      )}
                                                    >
                                                      {hasVariant(
                                                        variants,
                                                        "login",
                                                        "login"
                                                      ) ? (
                                                        <React.Fragment>
                                                          <React.Fragment>
                                                            {""}
                                                          </React.Fragment>
                                                          {
                                                            <h2
                                                              className={classNames(
                                                                projectcss.all,
                                                                projectcss.h2,
                                                                projectcss.__wab_text,
                                                                sty.h2___9GsgP,
                                                                {
                                                                  [sty.h2login___9GsgP7UOhc]:
                                                                    hasVariant(
                                                                      variants,
                                                                      "login",
                                                                      "login"
                                                                    )
                                                                }
                                                              )}
                                                            >
                                                              {hasVariant(
                                                                variants,
                                                                "login",
                                                                "login"
                                                              ) ? (
                                                                <React.Fragment>
                                                                  <React.Fragment>
                                                                    {""}
                                                                  </React.Fragment>
                                                                  {
                                                                    <h1
                                                                      className={classNames(
                                                                        projectcss.all,
                                                                        projectcss.h1,
                                                                        projectcss.__wab_text,
                                                                        sty.h1__cbqH,
                                                                        {
                                                                          [sty.h1login__cbqH7UOhc]:
                                                                            hasVariant(
                                                                              variants,
                                                                              "login",
                                                                              "login"
                                                                            )
                                                                        }
                                                                      )}
                                                                    >
                                                                      {hasVariant(
                                                                        variants,
                                                                        "login",
                                                                        "login"
                                                                      ) &&
                                                                      hasVariant(
                                                                        globalVariants,
                                                                        "screen",
                                                                        "tablet"
                                                                      ) ? (
                                                                        <React.Fragment>
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                          {
                                                                            <h2
                                                                              className={classNames(
                                                                                projectcss.all,
                                                                                projectcss.h2,
                                                                                projectcss.__wab_text,
                                                                                sty.h2__pNo9E,
                                                                                {
                                                                                  [sty.h2login__pNo9E7UOhc]:
                                                                                    hasVariant(
                                                                                      variants,
                                                                                      "login",
                                                                                      "login"
                                                                                    )
                                                                                }
                                                                              )}
                                                                            >
                                                                              {hasVariant(
                                                                                variants,
                                                                                "login",
                                                                                "login"
                                                                              ) &&
                                                                              hasVariant(
                                                                                globalVariants,
                                                                                "screen",
                                                                                "mobileOnly"
                                                                              ) ? (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC",
                                                                                      fontWeight: 900
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "trabalho em equipe ganha campeonatos."
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              ) : hasVariant(
                                                                                  variants,
                                                                                  "login",
                                                                                  "login"
                                                                                ) &&
                                                                                hasVariant(
                                                                                  globalVariants,
                                                                                  "screen",
                                                                                  "tablet"
                                                                                ) ? (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC",
                                                                                      fontWeight: 900
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "trabalho em equipe ganha campeonatos."
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              ) : (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "trabalho em equipe ganha campeonatos."
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              )}
                                                                            </h2>
                                                                          }
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                        </React.Fragment>
                                                                      ) : (
                                                                        <React.Fragment>
                                                                          <span
                                                                            className={
                                                                              "plasmic_default__all plasmic_default__span"
                                                                            }
                                                                            style={{
                                                                              color:
                                                                                "#FFFCFC"
                                                                            }}
                                                                          >
                                                                            {
                                                                              "trabalho em equipe ganha campeonatos."
                                                                            }
                                                                          </span>
                                                                        </React.Fragment>
                                                                      )}
                                                                    </h1>
                                                                  }
                                                                  <React.Fragment>
                                                                    {""}
                                                                  </React.Fragment>
                                                                  {
                                                                    <h4
                                                                      className={classNames(
                                                                        projectcss.all,
                                                                        projectcss.h4,
                                                                        projectcss.__wab_text,
                                                                        sty.h4__kQDk1,
                                                                        {
                                                                          [sty.h4login__kQDk17UOhc]:
                                                                            hasVariant(
                                                                              variants,
                                                                              "login",
                                                                              "login"
                                                                            )
                                                                        }
                                                                      )}
                                                                    >
                                                                      {hasVariant(
                                                                        variants,
                                                                        "login",
                                                                        "login"
                                                                      ) ? (
                                                                        <React.Fragment>
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                          {
                                                                            <h3
                                                                              className={classNames(
                                                                                projectcss.all,
                                                                                projectcss.h3,
                                                                                projectcss.__wab_text,
                                                                                sty.h3__yjYb8,
                                                                                {
                                                                                  [sty.h3login__yjYb87UOhc]:
                                                                                    hasVariant(
                                                                                      variants,
                                                                                      "login",
                                                                                      "login"
                                                                                    )
                                                                                }
                                                                              )}
                                                                            >
                                                                              {hasVariant(
                                                                                variants,
                                                                                "login",
                                                                                "login"
                                                                              ) ? (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "-Michael Jordan"
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              ) : (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "-Michael Jordan"
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              )}
                                                                            </h3>
                                                                          }
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                        </React.Fragment>
                                                                      ) : (
                                                                        <React.Fragment>
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                          {
                                                                            <h3
                                                                              className={classNames(
                                                                                projectcss.all,
                                                                                projectcss.h3,
                                                                                projectcss.__wab_text,
                                                                                sty.h3__yjYb8,
                                                                                {
                                                                                  [sty.h3login__yjYb87UOhc]:
                                                                                    hasVariant(
                                                                                      variants,
                                                                                      "login",
                                                                                      "login"
                                                                                    )
                                                                                }
                                                                              )}
                                                                            >
                                                                              {hasVariant(
                                                                                variants,
                                                                                "login",
                                                                                "login"
                                                                              ) ? (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "-Michael Jordan"
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              ) : (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "-Michael Jordan"
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              )}
                                                                            </h3>
                                                                          }
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                        </React.Fragment>
                                                                      )}
                                                                    </h4>
                                                                  }
                                                                  <React.Fragment>
                                                                    {""}
                                                                  </React.Fragment>
                                                                </React.Fragment>
                                                              ) : (
                                                                <React.Fragment>
                                                                  <span
                                                                    className={
                                                                      "plasmic_default__all plasmic_default__span"
                                                                    }
                                                                    style={{
                                                                      color:
                                                                        "#FFFCFC"
                                                                    }}
                                                                  >
                                                                    {
                                                                      "trabalho em equipe ganha campeonatos."
                                                                    }
                                                                  </span>
                                                                  <React.Fragment>
                                                                    {"\n"}
                                                                  </React.Fragment>
                                                                  {
                                                                    <h4
                                                                      className={classNames(
                                                                        projectcss.all,
                                                                        projectcss.h4,
                                                                        projectcss.__wab_text,
                                                                        sty.h4__kQDk1,
                                                                        {
                                                                          [sty.h4login__kQDk17UOhc]:
                                                                            hasVariant(
                                                                              variants,
                                                                              "login",
                                                                              "login"
                                                                            )
                                                                        }
                                                                      )}
                                                                    >
                                                                      {hasVariant(
                                                                        variants,
                                                                        "login",
                                                                        "login"
                                                                      ) ? (
                                                                        <React.Fragment>
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                          {
                                                                            <h3
                                                                              className={classNames(
                                                                                projectcss.all,
                                                                                projectcss.h3,
                                                                                projectcss.__wab_text,
                                                                                sty.h3__yjYb8,
                                                                                {
                                                                                  [sty.h3login__yjYb87UOhc]:
                                                                                    hasVariant(
                                                                                      variants,
                                                                                      "login",
                                                                                      "login"
                                                                                    )
                                                                                }
                                                                              )}
                                                                            >
                                                                              {hasVariant(
                                                                                variants,
                                                                                "login",
                                                                                "login"
                                                                              ) ? (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "-Michael Jordan"
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              ) : (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "-Michael Jordan"
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              )}
                                                                            </h3>
                                                                          }
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                        </React.Fragment>
                                                                      ) : (
                                                                        <React.Fragment>
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                          {
                                                                            <h3
                                                                              className={classNames(
                                                                                projectcss.all,
                                                                                projectcss.h3,
                                                                                projectcss.__wab_text,
                                                                                sty.h3__yjYb8,
                                                                                {
                                                                                  [sty.h3login__yjYb87UOhc]:
                                                                                    hasVariant(
                                                                                      variants,
                                                                                      "login",
                                                                                      "login"
                                                                                    )
                                                                                }
                                                                              )}
                                                                            >
                                                                              {hasVariant(
                                                                                variants,
                                                                                "login",
                                                                                "login"
                                                                              ) ? (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "-Michael Jordan"
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              ) : (
                                                                                <React.Fragment>
                                                                                  <span
                                                                                    className={
                                                                                      "plasmic_default__all plasmic_default__span"
                                                                                    }
                                                                                    style={{
                                                                                      color:
                                                                                        "#FFFCFC"
                                                                                    }}
                                                                                  >
                                                                                    {
                                                                                      "-Michael Jordan"
                                                                                    }
                                                                                  </span>
                                                                                </React.Fragment>
                                                                              )}
                                                                            </h3>
                                                                          }
                                                                          <React.Fragment>
                                                                            {""}
                                                                          </React.Fragment>
                                                                        </React.Fragment>
                                                                      )}
                                                                    </h4>
                                                                  }
                                                                  <React.Fragment>
                                                                    {""}
                                                                  </React.Fragment>
                                                                </React.Fragment>
                                                              )}
                                                            </h2>
                                                          }
                                                          <React.Fragment>
                                                            {""}
                                                          </React.Fragment>
                                                        </React.Fragment>
                                                      ) : (
                                                        <React.Fragment>
                                                          <span
                                                            className={
                                                              "plasmic_default__all plasmic_default__span"
                                                            }
                                                            style={{
                                                              color: "#FFFCFC"
                                                            }}
                                                          >
                                                            {
                                                              "trabalho em equipe ganha campeonatos."
                                                            }
                                                          </span>
                                                          <React.Fragment>
                                                            {"\n"}
                                                          </React.Fragment>
                                                          {
                                                            <h4
                                                              className={classNames(
                                                                projectcss.all,
                                                                projectcss.h4,
                                                                projectcss.__wab_text,
                                                                sty.h4__xrgEc
                                                              )}
                                                            >
                                                              <React.Fragment>
                                                                <React.Fragment>
                                                                  {""}
                                                                </React.Fragment>
                                                                {
                                                                  <h3
                                                                    className={classNames(
                                                                      projectcss.all,
                                                                      projectcss.h3,
                                                                      projectcss.__wab_text,
                                                                      sty.h3__a0X8
                                                                    )}
                                                                  >
                                                                    <React.Fragment>
                                                                      <span
                                                                        className={
                                                                          "plasmic_default__all plasmic_default__span"
                                                                        }
                                                                        style={{
                                                                          color:
                                                                            "#FFFCFC"
                                                                        }}
                                                                      >
                                                                        {
                                                                          "-Michael Jordan"
                                                                        }
                                                                      </span>
                                                                    </React.Fragment>
                                                                  </h3>
                                                                }
                                                                <React.Fragment>
                                                                  {""}
                                                                </React.Fragment>
                                                              </React.Fragment>
                                                            </h4>
                                                          }
                                                          <React.Fragment>
                                                            {""}
                                                          </React.Fragment>
                                                        </React.Fragment>
                                                      )}
                                                    </h1>
                                                  }
                                                  <React.Fragment>
                                                    {""}
                                                  </React.Fragment>
                                                </React.Fragment>
                                              ) : (
                                                <React.Fragment>
                                                  <span
                                                    className={
                                                      "plasmic_default__all plasmic_default__span"
                                                    }
                                                    style={{ color: "#FFFCFC" }}
                                                  >
                                                    {
                                                      "trabalho em equipe ganha campeonatos."
                                                    }
                                                  </span>
                                                  <React.Fragment>
                                                    {"\n"}
                                                  </React.Fragment>
                                                  {
                                                    <h4
                                                      className={classNames(
                                                        projectcss.all,
                                                        projectcss.h4,
                                                        projectcss.__wab_text,
                                                        sty.h4__enfjC
                                                      )}
                                                    >
                                                      <React.Fragment>
                                                        <React.Fragment>
                                                          {""}
                                                        </React.Fragment>
                                                        {
                                                          <h3
                                                            className={classNames(
                                                              projectcss.all,
                                                              projectcss.h3,
                                                              projectcss.__wab_text,
                                                              sty.h3__cuPtL
                                                            )}
                                                          >
                                                            <React.Fragment>
                                                              <span
                                                                className={
                                                                  "plasmic_default__all plasmic_default__span"
                                                                }
                                                                style={{
                                                                  color:
                                                                    "#FFFCFC"
                                                                }}
                                                              >
                                                                {
                                                                  "-Michael Jordan"
                                                                }
                                                              </span>
                                                            </React.Fragment>
                                                          </h3>
                                                        }
                                                        <React.Fragment>
                                                          {""}
                                                        </React.Fragment>
                                                      </React.Fragment>
                                                    </h4>
                                                  }
                                                  <React.Fragment>
                                                    {""}
                                                  </React.Fragment>
                                                </React.Fragment>
                                              )}
                                            </h1>
                                          }
                                          <React.Fragment>{""}</React.Fragment>
                                        </React.Fragment>
                                      </h2>
                                    }
                                    <React.Fragment>{""}</React.Fragment>
                                  </React.Fragment>
                                </h1>
                              }
                              <React.Fragment>{""}</React.Fragment>
                            </React.Fragment>
                          </div>
                        </div>
                      ) : null}
                    </div>
                  ) : null}
                </div>

                <div
                  className={classNames(projectcss.all, sty.column__qfE1, {
                    [sty.columnlogin__qfE17UOhc]: hasVariant(
                      variants,
                      "login",
                      "login"
                    )
                  })}
                >
                  {(
                    hasVariant(variants, "login", "login") &&
                    hasVariant(globalVariants, "screen", "tablet")
                      ? true
                      : hasVariant(variants, "login", "login")
                      ? true
                      : true
                  ) ? (
                    <SignInUp
                      data-plasmic-name={"signInUp"}
                      data-plasmic-override={overrides.signInUp}
                      className={classNames("__wab_instance", sty.signInUp, {
                        [sty.signInUplogin]: hasVariant(
                          variants,
                          "login",
                          "login"
                        )
                      })}
                    />
                  ) : null}
                  {(hasVariant(variants, "login", "login") ? true : true) ? (
                    <Login
                      data-plasmic-name={"login"}
                      data-plasmic-override={overrides.login}
                      className={classNames("__wab_instance", sty.login, {
                        [sty.loginlogin]: hasVariant(variants, "login", "login")
                      })}
                    />
                  ) : null}
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "columns",
    "helpingHand",
    "fraseMj",
    "signInUp",
    "login"
  ],
  header: ["header"],
  columns: ["columns", "helpingHand", "fraseMj", "signInUp", "login"],
  helpingHand: ["helpingHand"],
  fraseMj: ["fraseMj"],
  signInUp: ["signInUp"],
  login: ["login"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  columns: "div";
  helpingHand: typeof HelpingHand;
  fraseMj: "div";
  signInUp: typeof SignInUp;
  login: typeof Login;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    columns: makeNodeComponent("columns"),
    helpingHand: makeNodeComponent("helpingHand"),
    fraseMj: makeNodeComponent("fraseMj"),
    signInUp: makeNodeComponent("signInUp"),
    login: makeNodeComponent("login"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
